#ifndef  __MUZI_MERROR_H__
#define  __MUZI_MERROR_H__
#include<string>
#include<stdint.h>

#define MUZI_ERROR_TO_STRING(x) #x
enum MERROR
{
	MERROR_MAX = 1,

	// 完成并且无错
	COMPLETE = 0,
	FAILED = -1,

	// 文件系统
	NOADIR = -101,
	NOAFILE = -102,

	//文件系统错误
	DIRNOEXITS = -103,

	//sql错误
	SQLITE_OPEN_ERR = -201,
	SQLITE_CREATE_ERR = -202,
	SQLITE_CREATETABLE_ERR = -203,
	SQLITE_PREPARE_ERR = -204,
	SQL_NO_FOUND = -205,
	SQL_ID_ERR = -206,

	//输入参数错误
	ARG_IS_UNEXPECTED = -301,
	ARG_IS_NULL = -302,

	// 数据超出范围
	OUT_OF_RANGE = -303,
	OUT_OF_BUFF = -304,

	// 类型错误
	TYPE_ERR = -305,

	// 对象存在判断
	NOOBJECT = -306,
	UNUSEFUL = -307,
	OBJECT_IS_NULL = -308,

	// 网络
	MNET_IPADDRESS_FORMAT_CANNOT_ANALIZE = -401,
	MNET_ENDPOINT_IS_NO_CREATED = -402,
	MNET_RECV_ERROR = -403,
	MNET_SEND_ERROR = -404,
	MNET_READ_PENDING_NOW = -405,
	MNET_WRITE_PENDING_NOW = -406,

	MNET_OBJECT_IS_NO_SERVER = -407,
	MNET_OBJECT_IS_NO_CLIENT = -408,
	MNET_BIND_ERROR = -409,
	MNET_CONNECT_ERROR = -410,
	MNET_ACCEPT_ERROR = -411,
	MNET_LISTEN_ERROR = -412,
	MNET_SOCKET_SYSTEM_ERROR = -413,

	// 音视频
	MAV_STREAM_ID_NO_EXIT = -501, // stream id 不存在
	MAV_OBJECT_IS_NOT_USEFUL = -502, // 该对象不可用
	MAV_DECODER_NOT_FOUND = -503, // 解码器未找到
	MAV_DECODER_OPEN_FAILED = -504, // 解码器打开失败
	MAV_DECODER_SEND_PACKAGE_EOF = -505, // 解码器send package 到达末尾
	MAV_DECODER_SEND_PACKAGE_FAILED = -506, // 解码器 send package 失败
	MAV_DECODER_RECV_FRAME_EOF = -507,  // 解码器 recv frame 到达末尾
	MAV_DECODER_RECV_PACKAGE_FAILED = -508, // 解码器 recv frame 失败
	MAV_READER_OPEN_INPUT_FAILED = -509, // reader 打开输入流失败
	MAV_READER_FIND_STREAM_FAILED = -509, // reader 查找流失败
	MAV_DECODER_PACKAGE_NOT_MATCH = -510, // 解码器 所绑定的stream同 将要send的package 不匹配
	MAV_READER_TARGET_TYPE_STREAM_IS_NOT_FOUND = -511, // reader寻找目标类型的流时查找失败
	MAV_READER_TARGET_TYPE_STREAM_HAVE_NOT_MATCHED_DECODER = -512, // reader寻找目标类型的流时查找失败

	MERROR_MIN = INT_MIN,
};

#endif // ! __MUZI_MERROR_H__
