#pragma once
#ifndef __MUZI_CONFIGVALUE_H__
#define __MUZI_CONFIGVALUE_H__

//#define __MUZI_MLOGICSYSTEM_CONFIG_VALUE_MAX_LENGTH__ 1400
//#define __MUZI_MLOGICSYSTEM_CONFIG_VALUE_MAX_RECVQUE_LENGTH__ 10000
//#define __MUZI_MLOGICSYSTEM_CONFIG_VALUE_MAX_SENDVQUE_LENGTH__ 10000
//#define __MUZI_MLOGICSYSTEM_CONFIG_VALUE_MAX_LENGTH__ 1400
//#define __MUZI_MLOGICSYSTEM_CONFIG_VALUE_MAX_LENGTH__ 1400

enum MSG_IDS {
	MSG_HELLO_WORD = 1001,
};



#endif // !__MUZI_CONFIGVALUE_H__
